{
  "hash": "9f5a8c4e6d68a4021b89cdc6c2183526",
  "result": {
    "markdown": "---\ntitle: \"Week 3 Challenge Instructions\"\nauthor: \"Yakub Rabiutheen\"\ndescription: \"Degree and Density of a Network\"\ndate: \"03/06/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\n# editor: visual\ncategories: \n  - challenge_3\n  - instructions\n  # - railroads\n  # - faostat\n  # - wildbirds\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'tidyverse' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n-- Attaching packages --------------------------------------- tidyverse 1.3.2 --\nv ggplot2 3.3.5     v purrr   0.3.4\nv tibble  3.1.6     v dplyr   1.0.9\nv tidyr   1.2.0     v stringr 1.4.0\nv readr   2.1.2     v forcats 0.5.1\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'ggplot2' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'tibble' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'tidyr' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'readr' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'purrr' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'dplyr' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'stringr' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'forcats' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n-- Conflicts ------------------------------------------ tidyverse_conflicts() --\nx dplyr::filter() masks stats::filter()\nx dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(igraph)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'igraph' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'igraph'\n\nThe following objects are masked from 'package:dplyr':\n\n    as_data_frame, groups, union\n\nThe following objects are masked from 'package:purrr':\n\n    compose, simplify\n\nThe following object is masked from 'package:tidyr':\n\n    crossing\n\nThe following object is masked from 'package:tibble':\n\n    as_data_frame\n\nThe following objects are masked from 'package:stats':\n\n    decompose, spectrum\n\nThe following object is masked from 'package:base':\n\n    union\n```\n:::\n\n```{.r .cell-code}\nlibrary(statnet)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'statnet' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: tergm\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'tergm' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: ergm\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'ergm' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: network\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'network' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\n'network' 1.18.1 (2023-01-24), part of the Statnet Project\n* 'news(package=\"network\")' for changes since last version\n* 'citation(\"network\")' for citation information\n* 'https://statnet.org' for help, support, and other information\n\n\nAttaching package: 'network'\n\nThe following objects are masked from 'package:igraph':\n\n    %c%, %s%, add.edges, add.vertices, delete.edges, delete.vertices,\n    get.edge.attribute, get.edges, get.vertex.attribute, is.bipartite,\n    is.directed, list.edge.attributes, list.vertex.attributes,\n    set.edge.attribute, set.vertex.attribute\n\n\n'ergm' 4.4.0 (2023-01-26), part of the Statnet Project\n* 'news(package=\"ergm\")' for changes since last version\n* 'citation(\"ergm\")' for citation information\n* 'https://statnet.org' for help, support, and other information\n\n'ergm' 4 is a major update that introduces some backwards-incompatible\nchanges. Please type 'news(package=\"ergm\")' for a list of major\nchanges.\n\nLoading required package: networkDynamic\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'networkDynamic' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\n'networkDynamic' 0.11.3 (2023-02-15), part of the Statnet Project\n* 'news(package=\"networkDynamic\")' for changes since last version\n* 'citation(\"networkDynamic\")' for citation information\n* 'https://statnet.org' for help, support, and other information\n\nRegistered S3 method overwritten by 'tergm':\n  method                   from\n  simulate_formula.network ergm\n\n'tergm' 4.1.1 (2022-11-07), part of the Statnet Project\n* 'news(package=\"tergm\")' for changes since last version\n* 'citation(\"tergm\")' for citation information\n* 'https://statnet.org' for help, support, and other information\n\n\nAttaching package: 'tergm'\n\nThe following object is masked from 'package:ergm':\n\n    snctrl\n\nLoading required package: ergm.count\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'ergm.count' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\n'ergm.count' 4.1.1 (2022-05-24), part of the Statnet Project\n* 'news(package=\"ergm.count\")' for changes since last version\n* 'citation(\"ergm.count\")' for citation information\n* 'https://statnet.org' for help, support, and other information\n\nLoading required package: sna\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'sna' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: statnet.common\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'statnet.common' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'statnet.common'\n\nThe following object is masked from 'package:ergm':\n\n    snctrl\n\nThe following objects are masked from 'package:base':\n\n    attr, order\n\nsna: Tools for Social Network Analysis\nVersion 2.7-1 created on 2023-01-24.\ncopyright (c) 2005, Carter T. Butts, University of California-Irvine\n For citation information, type citation(\"sna\").\n Type help(package=\"sna\") to get started.\n\n\nAttaching package: 'sna'\n\nThe following objects are masked from 'package:igraph':\n\n    betweenness, bonpow, closeness, components, degree, dyad.census,\n    evcent, hierarchy, is.connected, neighborhood, triad.census\n\nLoading required package: tsna\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'tsna' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\n'statnet' 2019.6 (2019-06-13), part of the Statnet Project\n* 'news(package=\"statnet\")' for changes since last version\n* 'citation(\"statnet\")' for citation information\n* 'https://statnet.org' for help, support, and other information\n\nunable to reach CRAN\n```\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\n```\n:::\n\n\n## Challenge Overview\n\nDescribe the many measures of degree, as well as density, of a network and compare \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(igraph)\nlibrary(network)\n```\n:::\n\n## Degree\n\nReading in Climate Data.\n\nThe Climate Dataframe has a Semicolor for it's Seperator.\n\n::: {.cell}\n\n```{.r .cell-code}\nclimate_df <- read.csv(\"climate0205-allop.csv\", sep =  \";\") \n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nclimate_df <- climate_df %>% subset(select = -c(X))\n```\n:::\n\n\n\n\nNow Turning the Climate Dataframe into an igraph Object and then a Network.\n\n::: {.cell}\n\n```{.r .cell-code}\nclimate.ig <- graph_from_adjacency_matrix(as.matrix(climate_df), weighted = TRUE, mode = \"directed\", add.rownames = TRUE)\nclimate.net <- as.network(as.matrix(climate_df), directed = TRUE, weighted = TRUE)\n```\n:::\n\n\nPrinting the Network Attributes\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(climate.net)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Network attributes:\n  vertices = 34 \n  directed = TRUE \n  hyper = FALSE \n  loops = FALSE \n  multiple = FALSE \n  bipartite = FALSE \n  total edges= 291 \n    missing edges= 0 \n    non-missing edges= 291 \n\n Vertex attribute names: \n    vertex.names \n\nNo edge attributes\n```\n:::\n:::\n\n\n Network attributes:\n  vertices = 34 \n  directed = TRUE \n  hyper = FALSE \n  loops = FALSE \n  multiple = FALSE \n  bipartite = FALSE \n  total edges= 291 \n    missing edges= 0 \n    non-missing edges= 291 \n\n\nThe Climate  network has 34 vertices and is undirected, with bidirectional connections between entities. There are no loops or multiple edges present, indicating a simpler structure. The bipartite nature of the network divides the vertices into two distinct sets. In total, there are 34 edges representing the direct relationships between entities, with no missing connections in the network representation.\n\n# Dyad Census\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndyad.census(climate.net)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     Mut Asym Null\n[1,]  65  161  335\n```\n:::\n:::\n\n     Mut Asym Null\n[1,]  65  161  335\n-65 mutually connected dyads, indicating bidirectional connections between pairs of entities. \n- 151 Asymmetrical \n-365 Null dyads.\n\n\n# Triad Census\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntriad.census(climate.net)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      003  012 102 021D 021U 021C 111D 111U 030T 030C 201 120D 120U 120C 210\n[1,] 1644 1641 497  347  255  231  239  314  175    3 126  100  116   81 164\n     300\n[1,]  51\n```\n:::\n:::\n\n      003  012 102 021D 021U 021C 111D 111U 030T 030C 201 120D 120U 120C 210 300\n[1,] 1644 1641 497  347  255  231  239  314  175    3 126  100  116   81 164  51\n\nTriad Census\n-1644 triads with no ties, suggesting the presence of isolated entities or disconnected clusters within the network\n\n\n\n##Create Climate Node\n\n\n::: {.cell}\n\n```{.r .cell-code}\nname <- climate.net %v% \"vertex.names\"\ndegree <- degree(climate.net)\nindegree <- degree(climate.net, cmode = \"indegree\")\noutdegree <- degree(climate.net, cmode = \"outdegree\")\n\nclimate.nodes <- data.frame(\n  name = name,\n  degree = degree,\n  indegree = indegree,\n  outdegree = outdegree\n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(climate.nodes$degree)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17.11765\n```\n:::\n:::\n\n\nAverage is 17.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(climate.nodes)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     name               degree         indegree        outdegree     \n Length:34          Min.   : 2.00   Min.   : 0.000   Min.   : 0.000  \n Class :character   1st Qu.:10.00   1st Qu.: 5.250   1st Qu.: 3.000  \n Mode  :character   Median :16.50   Median : 7.500   Median : 8.000  \n                    Mean   :17.12   Mean   : 8.559   Mean   : 8.559  \n                    3rd Qu.:21.00   3rd Qu.:11.000   3rd Qu.:11.000  \n                    Max.   :40.00   Max.   :22.000   Max.   :29.000  \n```\n:::\n:::\n\n     name               degree         indegree        outdegree     \n Length:34          Min.   : 2.00   Min.   : 0.000   Min.   : 0.000  \n Class :character   1st Qu.:10.00   1st Qu.: 5.250   1st Qu.: 3.000  \n Mode  :character   Median :16.50   Median : 7.500   Median : 8.000  \n                    Mean   :17.12   Mean   : 8.559   Mean   : 8.559  \n                    3rd Qu.:21.00   3rd Qu.:11.000   3rd Qu.:11.000  \n                    Max.   :40.00   Max.   :22.000   Max.   :29.000  \n\n-34 vertices in total, \n\n-the degree distribution ranges from a minimum of 2 to a maximum of 40. =\n\n- The median degree of 16.5 further reinforces this observation, indicating that half of the vertices have a degree of 16 or lower\n\n\n## Density\n\nCompute the density of the network. Is this a global or local measure? Does it have a relationship with average degree? \n\n\n::: {.cell}\n\n```{.r .cell-code}\nnetwork.density(climate.net)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.2593583\n```\n:::\n:::\n\n[1] 0.2593583\nThe Density is 0.259, which indicates approximately 25.9% of the possible edges are present in the network. \n\n\nDensity is  a global measure that quantifies the proportion of actual edges present in the network compared to the total number of possible edges. \n\nWith an average degree of 17.17 and a density of 0.259, we observe a moderate level of connectivity in the \"climate.nodes\" network. The average degree signifies a relatively high number of edges per vertex, indicating a denser network. \n\n\n## Random Network\n\nCreate a random (Erdos-Renyi) network with the same number of nodes and edges than the network of your choice. On `igraph`, the necessary commands are `random.graph.game(n, p.or.m, type = c(\"gnp\", \"gnm\"), directed = FALSE, loops = FALSE)` (deprecated), `sample_gnp(n, p, directed = FALSE, loops = FALSE)` or `sample_gnm(n, m, directed = FALSE, loops = FALSE)`. The `p.or.m` argument is to specify the probability of an edge $p$ or the number of edges $m$.\n  \nCompare the densities, dyad and triad censuses, and degree distributions, with the measures of the network of your choice. Does the comparison us something about the network of your choice? \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nrandom.ig <- sample_gnm(34, 291)\ndyads <- dyad_census(random.ig)\ntriads <- triad_census(random.ig)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in triad_census(random.ig): At core/misc/motifs.c:1165 : Triad census\ncalled on an undirected graph.\n```\n:::\n\n```{.r .cell-code}\ndensity <- edge_density(random.ig)\ndegrees <- igraph::degree(random.ig)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(dyads)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     Length Class  Mode   \nmut  1      -none- numeric\nasym 1      -none- numeric\nnull 1      -none- numeric\n```\n:::\n\n```{.r .cell-code}\nsummary(triads)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n    0.0     0.0     0.0   374.0   171.5  2334.0 \n```\n:::\n\n```{.r .cell-code}\nsummary(density)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.5187  0.5187  0.5187  0.5187  0.5187  0.5187 \n```\n:::\n:::\n\n\n> summary(triads)\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n    0.0     0.0     0.0   374.0   171.5  2334.0 \n> summary(density)\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.5187  0.5187  0.5187  0.5187  0.5187  0.5187 \n\n\nBoth networks have the same density of 0.5187, indicating a similar level of overall connectivity in terms of edge presence relative to the total number of possible edges. However, the Climate Network had more complete triads compared to the randomly generated graph",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}